import os
import random
import requests
from docx import Document

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_URL = "https://api.deepseek.com/v1/chat/completions"

# Fallback palette for arbitrary sections
FALLBACK_META = [
    ("💼", "blue"),
    ("🏢", "sky"),
    ("🌐", "indigo"),
    ("🧩", "purple"),
    ("📊", "green"),
    ("📈", "emerald"),
    ("👥", "yellow"),
    ("⚠️", "red"),
    ("💡", "pink"),
    ("🧠", "gray"),
]

# 🔄 UPDATED SECTION EXTRACTOR
def extract_sections_from_docx(docx_path):
    doc = Document(docx_path)
    sections = {}
    current_heading = None
    current_text = []

    for para in doc.paragraphs:
        text = para.text.strip()
        style_name = para.style.name.lower()

        # Use heading styles as section titles
        if "heading" in style_name:
            if current_heading and current_text:
                sections[current_heading] = "\n".join(current_text).strip()
            current_heading = text
            current_text = []
        else:
            current_text.append(text)

    if current_heading and current_text:
        sections[current_heading] = "\n".join(current_text).strip()

    return sections


def summarize_section_with_deepseek(section_title, section_text):
    prompt = f"""
You are an institutional research analyst preparing a financial infographic.

Summarize the section titled "{section_title}" into 3 to 5 concise bullet points.
Each point should be a single sentence, highlighting key insights clearly and professionally.

Section:
\"\"\"{section_text}\"\"\"
"""
    headers = {"Authorization": f"Bearer {DEEPSEEK_API_KEY}"}
    payload = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0.3
    }
    response = requests.post(DEEPSEEK_URL, headers=headers, json=payload)
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"].strip()


def assign_icon_and_color(index):
    return FALLBACK_META[index % len(FALLBACK_META)]


def build_infographic_html(company_name, sections):
    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>{company_name} – Infographic</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    body {{
      font-family: 'Inter', sans-serif;
      background-color: #f9fafb;
      color: #1f2937;
    }}
    .section-icon {{
      font-size: 1.4rem;
      margin-right: 0.6rem;
    }}
  </style>
</head>
<body class="px-6 py-8 max-w-7xl mx-auto">
  <h1 class="text-3xl font-bold text-center text-blue-800 mb-2">{company_name} – Investment Memo Infographic</h1>
  <p class="text-center text-sm text-gray-500 mb-10">Generated by Aranca GenAI Platform</p>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
"""

    for idx, (title, section_text) in enumerate(sections.items()):
        icon, color = assign_icon_and_color(idx)
        print(f"🔍 Summarizing section: {title}")
        summary = summarize_section_with_deepseek(title, section_text)

        lines = [
            line.strip("•- ").strip()
            for line in summary.split("\n")
            if line.strip()
        ]
        bullet_items = "\n".join(f"<li>{line}</li>" for line in lines)

        html += f"""
    <div class="shadow-md rounded-xl p-5 transition-transform hover:scale-[1.02] duration-200 border-l-4 border-{color}-600 bg-{color}-50">
      <h2 class="text-lg font-semibold text-gray-800 mb-3 flex items-center">
        <span class="section-icon">{icon}</span>{title}
      </h2>
      <ul class="list-disc text-sm text-gray-700 space-y-1 pl-5 leading-relaxed">
        {bullet_items}
      </ul>
    </div>
"""

    html += """
  </div>
</body>
</html>
"""
    return html


def generate_infographic_html(docx_path, company_name, output_path):
    print("📄 Extracting memo sections...")
    sections = extract_sections_from_docx(docx_path)

    if not sections:
        print("⚠️ No sections extracted. Check that your DOCX uses heading styles.")
        return

    print("🎨 Generating HTML infographic...")
    html = build_infographic_html(company_name, sections)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"✅ Infographic saved to: {output_path}")
